### ISSUE TITLE
Please remove all Mod Menu name and branding

### ISSUE THREAD

**Issue by Prospector** [Flintloader-Modules/modmenu#1]
I would like to request that you remove all Mod Menu logos and branding from this project as well as somehow change the name so it either is not "Mod Menu" or includes the term "Unofficial" or something to indicate it is a different project. In addition, please do not link to my wiki or anything as I do not want to receive people from this project asking me for help.

**Comment by hypherionmc** [comment]
Hi Prospector. 

I actually still wanted to reach out to you, but seems you got to me first.

I will do that. Most of the modules on here are just used as proof of concept modules, and I have no plans to release any of them on curse or modrinth, without contacting the authors in advance

**Comment by Prospector** [comment]
Ok, sounds good. Could even call it "Module Menu" or something if you wanted. 

By the way, since finding this project my main question is why? I assume this is some sort of abstraction layer for the client-side since you compare it to Spigot/paper, but why not build it on top of standard Fabric loader? I'm a little unsure why it needs to diverge and not be compatible with fabric mods out of the box

**Comment by hypherionmc** [comment]
So short description is, it's kinda an attempt at a modern LiteLoader. The idea is to give people a way to use mods on vanilla/spigot servers, without the heavy overhead of a full blown modloader.

The reason for not just building it right on top of Fabric is mostly for me to learn more about the inner workings of modloaders and core minecraft modifications. It was also done since the loader aims to be client only, so that users don't attempt to load a fabric server mod, or even a fabric mod that requires installation both sides, on their client.

Another smaller reason is so that it doesn't look like another loader split (aka fabric and quilt), but something on it's own. This is actually just a hobby and learning project, but it appears to have caught more attention than I expected

**Comment by Prospector** [comment]
thanks!
